# Generated by Django 2.1.15 on 2020-12-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catalogue',
        ),
        migrations.AddField(
            model_name='product',
            name='catalogue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Catalogue'),
        ),
    ]
