# Generated by Django 2.1.15 on 2020-12-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address2',
        ),
    ]
