# Generated by Django 2.1.15 on 2020-12-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201225_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ZipCode',
            field=models.IntegerField(),
        ),
    ]
