# Generated by Django 2.1.15 on 2020-12-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201225_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Fname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
