# Generated by Django 2.1.15 on 2020-12-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201225_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
