# Generated by Django 2.1.15 on 2021-01-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='Status',
        ),
    ]
