# Generated by Django 2.1.15 on 2021-01-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210103_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='PhoneNumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Status',
            new_name='status',
        ),
    ]
