# Generated by Django 2.1.15 on 2021-01-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210122_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
