# Generated by Django 2.1.15 on 2021-01-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
